name: ai-eng-week5
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - notebook
  - jupyterlab
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - joblib=1.4.2
  - numpy=1.26.4
  - matplotlib=3.8.4
